/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/9.0.35
 * Generated at: 2020-05-27 18:27:57 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp._1;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import java.sql.*;
import javax.sql.*;
import java.sql.DriverManager;

public final class _1logged_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("java.sql");
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("javax.sql");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("java.sql.DriverManager");
  }

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
      throws java.io.IOException, javax.servlet.ServletException {

    if (!javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("<!DOCTYPE HTML>\n");
      out.write("<html lang=\"ro\">\n");
      out.write("<head>\n");
      out.write("<meta charset=\"UTF-8\">\n");
      out.write("<title>Problema 1 - logged</title>\n");
      out.write("  <body>\n");
      out.write("    <form action=\"1logged.jsp\" method=\"POST\">\n");
      out.write("    \t<input type=\"submit\" name=\"logoutButton\" value=\"Logout\" >\n");
      out.write("  </form>\n");
      out.write("    ");


      if(session.getAttribute("user") == null){
        response.sendRedirect("1.jsp");
      }


      String driver = "com.mysql.jdbc.Driver";
      Class.forName(driver);
      java.sql.Connection con = DriverManager.getConnection("jdbc:mysql://localhost/db?serverTimezone=UTC","root","");

      String logoutButton = request.getParameter("logoutButton");
      if(logoutButton!=null && logoutButton.equals("Logout")){
        response.sendRedirect("1.jsp");
      }

    
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("    ");


    String addButton = request.getParameter("moderateButton");
    String removeButton = request.getParameter("moderateButton3");

    if(addButton!=null && addButton.equals("Accept"))
    {
      int idComment = Integer.parseInt(request.getParameter("moderateButton2"));
      PreparedStatement ps = con.prepareStatement("UPDATE comments SET moderated=1 where id=?");
      int moderated = 0;
  		ps.setInt(1, idComment);
  		ps.execute();
    }else if(removeButton!=null && removeButton.equals("Remove")){
      int idComment = Integer.parseInt(request.getParameter("moderateButton4"));
      PreparedStatement ps = con.prepareStatement("DELETE FROM comments where id=?");
      int moderated = 0;
  		ps.setInt(1, idComment);
  		ps.execute();
    }

    
      out.write("\n");
      out.write("\n");
      out.write("    ");

    
      out.write("<b>Comments</b> <br>");

    Statement st= con.createStatement();
    ResultSet rs=st.executeQuery("SELECT * FROM comments WHERE moderated=0");
    while(rs.next())
    {
          
      out.write("\n");
      out.write("            <tr>\n");
      out.write("                  <td><b>");
      out.print(rs.getString("user") );
      out.write(": </b></td>\n");
      out.write("                  <td>");
      out.print(rs.getString("comment") );
      out.write("</td>\n");
      out.write("            </tr>\n");
      out.write("            <form action=\"1logged.jsp\" method=\"POST\">\n");
      out.write("              <input type=\"submit\" name=\"moderateButton\" value=\"Accept\">\n");
      out.write("              <input type=\"hidden\" name=\"moderateButton2\" value=");
      out.print(rs.getString("id") );
      out.write(" readonly>\n");
      out.write("            </form>\n");
      out.write("            <form action=\"1logged.jsp\" method=\"POST\">\n");
      out.write("              <input type=\"submit\" name=\"moderateButton3\" value=\"Remove\">\n");
      out.write("              <input type=\"hidden\" name=\"moderateButton4\" value=");
      out.print(rs.getString("id") );
      out.write(" readonly>\n");
      out.write("            </form>\n");
      out.write("            <br>\n");
      out.write("          ");

    }

    
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("\n");
      out.write("</body>\n");
      out.write("</html>\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
